spring:
  application:
    name: spring-boot-jpa-tutorial

  datasource:
    url: jdbc:mysql://localhost:3306/schooldb
    username: root
    password: Thought@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
